version: "2"
services:
  portainer:
    image: portainer:20200329_212642
    volumes:
      - /var/run/docker.sock: /var/run/docker.sock
    ports:
      - 9000: 9000
    restart: always
    net: host
 
  ishou_mariadb_infra:
    depends_on:
      - portainer
    image: mariadb:20200329_204923
    ports:
      - 3306: 3306
    volumes:
      - /home/tim/data/ishou/data/mariadb: /var/lib/mysql
    restart: always
    net: host
    environment:
      MYSQL_ROOT_PASSWORD: 123456
 
  ishou_redis_infra:
    depends_on:
      - portainer
    image: redis:20200329_204223
    ports:
      - 6379: 6379
    volumes:
      - /home/tim/data/ishou/data/redis: /data
    command: redis-server --appendonly yes --requirepass 123456
    restart: always
    net: host

  ishou_nginx_infra:
    depends_on:
      - portainer
    image: nginx:20200329_204023
    ports:
      - 80: 80
    volumes:
      - /home/tim/data/ishou/data/nginx/conf/nginx.conf: /etc/nginx/nginx.conf
      - /home/tim/data/ishou/data/nginx/web: /usr/share/nginx/html
      - /home/tim/data/ishou/data/nginx/log: /var/log/nginx
    restart: always
    net: host

  ishou_mariadb_init:
    depends_on:
      - ishou_mariadb_infra
    image: ishou_mariadb_init:v1.0_dev_20200406_134258_9fe38fb
    ports:
      - 3307: 3306
    volumes:
      - /home/tim/data/ishou/data/init/mariadb/backup: /home/mysql/backup
    restart: none
    net: host
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  ishou_eureka_service:
    depends_on:
      - portainer
    image: eureka-server:20200329_183226_1c6152e
    ports:
      - 9999: 9999
    restart: always
    net: host

  ishou_auth_service:
    depends_on:
      - ishou_eureka_service
      - ishou_mariadb_infra
      - ishou_redis_infra
    image: auth:20200329_190450_4367395
    ports:
      - 9091: 9091
    restart: always
    net: host

  ishou_site_service:
    depends_on:
      - ishou_auth_service
    image: ishou-service-site:20200329_183549_7524176
    ports:
      - 9092: 9092
    restart: always
    net: host

  ishou_web:
    depends_on:
      - ishou_nginx_infra
    image: ishou-web:v1.0_dev_20200406_103732_c1f52a6
    restart: none
    net: host
    volumes:
      - /home/tim/data/ishou/data/nginx/web: /opt/project/web